# Generated by Django 3.0.5 on 2020-05-22 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthYear', models.CharField(choices=[('Januari 2020', 'Januari 2020'), ('Februari 2020', 'Februari 2020'), ('Maret 2020', 'Maret 2020'), ('April 2020', 'April 2020'), ('Mei 2020', 'Mei 2020'), ('Juni 2020', 'Juni 2020'), ('Juli 2020', 'Juli 2020'), ('Agustus 2020', 'Agustus 2020'), ('September 2020', 'September 2020'), ('Oktober 2020', 'Oktober 2020'), ('November 2020', 'November 2020'), ('Desember 2020', 'Desember 2020')], max_length=200, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='budget',
            name='month',
        ),
        migrations.RemoveField(
            model_name='budget',
            name='year',
        ),
        migrations.DeleteModel(
            name='Month',
        ),
        migrations.DeleteModel(
            name='Year',
        ),
        migrations.AddField(
            model_name='budget',
            name='monthYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget.MonthYear'),
        ),
    ]
