# Generated by Django 3.0.5 on 2020-05-28 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200522_0328'),
    ]

    operations = [
        migrations.AddField(
            model_name='budget',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
