# Generated by Django 3.0.5 on 2020-05-30 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_budget_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='totalBiaya',
            field=models.IntegerField(null=True),
        ),
    ]
