# Generated by Django 3.0.5 on 2020-05-13 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('notes', '0003_auto_20200513_0454'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Title',
            new_name='Topic',
        ),
        migrations.RenameField(
            model_name='topic',
            old_name='title',
            new_name='topic',
        ),
        migrations.AddField(
            model_name='note',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.Topic'),
        ),
        migrations.AlterField(
            model_name='note',
            name='notes',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
