# Generated by Django 3.0.5 on 2020-05-25 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_coba'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='clear',
            field=models.BooleanField(default=False),
        ),
    ]
