# Generated by Django 3.0.5 on 2020-05-28 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_note_clear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coba',
        ),
    ]
